### ISSUE TITLE
[버그] ios simulator에서 테스트 시 네트워킹 에러

### ISSUE THREAD

**Issue by ybh1760** [orange-mush/pickk-app#12]
**버그 설명**
 ios simulator에서 포스트 와 랭킹 아이템 쿼리시 네트워킹에러 발생

**To Reproduce**

1. react-native run-ios실행
2. 포스트나 랭킹 스크린 보기

**Expected behavior**
네트워크 문제없이 리스트 아이템 화면에 출력

**Screenshots**
<img width="394" alt="Screen Shot 2020-01-12 at 10 59 15 PM" src="https://user-images.githubusercontent.com/50945365/72220026-ca5e6200-358f-11ea-8247-4ff39803fcca.png">

**Comment by orange-mush** [comment]
<img width="368" alt="Screen Shot 2020-01-20 at 3 25 47 AM" src="https://user-images.githubusercontent.com/48555121/72686117-8ee60980-3b34-11ea-9c17-592f735f185c.png">
나는 잘 되는데
`cd ios && pod install`한번 실행해보삼
